source 'https://rubygems.org'

gem 'rake'
gem 'redgreen'
gem 'jeweler'
gem 'rails', '~> 3.0.3'
gem 'minitest-spec-rails', '~> 4.7'
gem 'activerecord', :require => 'active_record'
gem 'activesupport', :require => 'active_support'
gem 'actionpack', :require => 'action_pack'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'pry'
